apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: demo-vcluster-clusterissuer
spec:
  acme:
    email: YOUR_EMAIL_ADDRESS
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
