{
 "title": "ETCD Latency",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "API Server Request ( Secrets ) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(apiserver_request_total{resource=\"secrets\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total sum of all observed request latencies (seconds)",
   "type": "timeseries",
   "description": "Total sum of all observed request latencies (seconds)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(etcd_request_duration_seconds_sum{type=\"secrets\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(apiserver_request_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD Rate (Secrets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(etcd_requests_total{type=\"secrets\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}