apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "eks-vcluster-platform"
  region: "us-west-1"
  version: "1.30"
  tags:
    karpenter.sh/discovery: "eks-vcluster-platform"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: external-dns
        namespace: external-dns
      wellKnownPolicies:
        externalDNS: true
    - metadata:
        namespace: cert-manager
        name: cert-manager
      wellKnownPolicies:
        certManager: true
    - metadata:
        namespace: kube-system
        name: aws-load-balancer-controller
      wellKnownPolicies:
        awsLoadBalancerController: true

vpc:
  manageSharedNodeSecurityGroupRules: true
  cidr: "172.31.0.0/17"

managedNodeGroups:
  - name: managed-t3a
    instanceType: "t3a.small"
    minSize: 1
    maxSize: 3
    desiredCapacity: 2

karpenter:
  version: "v0.31.3" # Exact version must be provided
  createServiceAccount: true # default is false
  withSpotInterruptionQueue: true # adds all required policies and rules for supporting Spot Interruption Queue, default is false

addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
    wellKnownPolicies: # add IAM and service account
      ebsCSIController: true
